---
title: "Optimization"
author: "Deepak Bastola"
date: "December 14, 2020"
output: html_document
---


```{r, message=FALSE}
# Call the libraries
library(mvtnorm)

```


```{r}
# Metropolis Hasting Sampler

metrop <- function(func, thetaInit, Nburnin, Nsamp, sampleCov, verbose, 
                   demo=FALSE, ...) {

  Ntheta   <- length(thetaInit)
  thetaCur <- thetaInit
  funcCur  <- func(thetaInit, ...) # log10
  funcSamp <- matrix(data=NA, nrow=Nsamp, ncol=2+Ntheta) 
  
  # funcSamp will be filled and returned
  nAccept  <- 0
  acceptRate <- 0
  if(demo) {
    thetaPropAll <- matrix(data=NA, nrow=Nsamp, ncol=Ntheta)
  }
  
  for(n in 1:(Nburnin+Nsamp)) {

    # Metropolis algorithm. No Hastings factor for symmetric proposal
    if(is.null(dim(sampleCov))) { # theta and sampleCov are scalars
      thetaProp <- rnorm(n=1, mean=thetaCur, sd=sqrt(sampleCov))
    } else {
      thetaProp <- rmvnorm(n=1, mean=thetaCur, sigma=sampleCov, 
                           method="eigen")
    }
    funcProp  <- func(thetaProp, ...) 
    logMR <- sum(funcProp) - sum(funcCur) # log10 of the Metropolis ratio
    #cat(n, thetaCur, funcCur, ":", thetaProp, funcProp, "\n")
    if(logMR>=0 || logMR>log10(runif(1, min=0, max=1))) {
      thetaCur   <- thetaProp
      funcCur    <- funcProp
      nAccept    <- nAccept + 1
      acceptRate <- nAccept/n
    }
    if(n>Nburnin) {
      funcSamp[n-Nburnin,1:2] <- funcCur
      funcSamp[n-Nburnin,3:(2+Ntheta)] <- thetaCur
      if(demo) {
        thetaPropAll[n-Nburnin,1:Ntheta] <- thetaProp
      }
    }

    # Diagnostics
    if( is.finite(verbose) && (n%%verbose==0 || n==Nburnin+Nsamp) ) {
      s1 <- noquote(formatC(n,          format="d", digits=5, flag=""))
      s2 <- noquote(formatC(Nburnin,    format="g", digits=5, flag=""))
      s3 <- noquote(formatC(Nsamp,      format="g", digits=5, flag=""))
      s4 <- noquote(formatC(acceptRate, format="f", digits=4, width=7, 
                            flag=""))
      cat(s1, "of", s2, "+", s3, s4, "\n")
    }

  }

  if(demo) {
    return(list(funcSamp=funcSamp, thetaPropAll=thetaPropAll))
  } else {
    return(funcSamp)
  }
 
}

```



```{r}
# 

set.seed(50)
Ndat <- 20
x <- sort(runif(Ndat, 0, 10))
sigTrue <- 2
modMat <- c(-2, -1, 1)

y <- cbind(1,x,x^2) %*% as.matrix(modMat) + rnorm(Ndat, 0, sigTrue)
y <- drop(y)


thetaTrue <- c(modMat[1], atan(modMat[2]), modMat[3], log10(sigTrue))
xMean <- mean(x)
yMean <- mean(y)
obsdata <- data.frame(cbind(x = x - xMean,y = y - yMean)) # columns must be named "x" and "y"
rm(x,y)

#metropolis hastings

sampleCov <- diag(c(0.01, 0.01, 0.04, 0.04)^2)
thetaInit <- c(2, pi, log10(23))

thetaInit <- c(2, atan(-1), 1.18, log10(2.4))

# Return c(log10(prior), log10(likelihood)) (each generally unnormalized) of the quadratic model
logpost.quadraticmodel <- function(theta, obsdata) {
  logprior <- logprior.quadraticmodel(theta)
  if(is.finite(logprior)) { # only evaluate model if parameters are sensible
    return( c(logprior, loglike.quadraticmodel(theta, obsdata)) )
  } else {
    return( c(-Inf, -Inf) )
  }
}

# Return log10(likelihood) for parameters theta and obsdata
# dnorm(..., log=TRUE) returns log base e, so multiply by 1/ln(10) = 0.4342945
# to get log base 10
loglike.quadraticmodel <- function(theta, obsdata) {
  # convert alpha to b_1 and log10(ysig) to ysig
  theta[2] <- tan(theta[2])
  theta[4] <- 10^theta[4]
  modPred <- drop( theta[1:3] %*% t(cbind(1,obsdata$x,obsdata$x^2)) )
  # Dimensions in above mixed vector/matrix multiplication: [Ndat] = [P] %*% [P x Ndat] 
  logLike <- (1/log(10))*sum( dnorm(modPred - obsdata$y, mean=0, sd=theta[4], log=TRUE) )
  return(logLike)
}

# Return log10(unnormalized prior)
logprior.quadraticmodel <- function(theta) {
  b0Prior      <- dnorm(theta[1], mean=0, sd=10)
  alphaPrior   <- 1
  b2Prior      <- dnorm(theta[3], mean=0, sd=5)
  logysigPrior <- 1 
  logPrior <- sum( log10(b0Prior), log10(alphaPrior), log10(b2Prior), log10(logysigPrior) )
  return(logPrior)
}

allSamp <- metrop(func=logpost.quadraticmodel, thetaInit=thetaInit, Nburnin=0, Nsamp=1e5,
                   sampleCov=sampleCov, verbose=1e3, obsdata=obsdata)


chain <- allSamp[,3:6]
boxplot(chain, horizontal = TRUE)

p.1 = 4
e.ind.m4q = rep(1,p.1)
q.ind.m4q = c(rep(.16,p.1),rep(.84,p.1),rep(.025,p.1),rep(.975,p.1))
col.q.m4q = c(rep(1:p.1,4))
mbm.G.m4q = mbm.g(chain, e.ind.m4q, q.ind.m4q, col.q.m4q, est.type = "BM")
cov.G.m4q = mbm.G.m4q$Cov
est.G.m4q = mbm.G.m4q$Est
m.int.m4q = n.sim.int(Sigma=cov.G.m4q,conf=.9,center=est.G.m4q,
	epsilon=.001)$ints
in.cred.ible(chain,est.G.m4q,m.int.m4q)

```




















```